Repository JungDohyeon/MC3-Team14-FutureStarz, pull requests merged in 2023-07, with the labels that each got.

#17 [FEAT] #16 Setting ColorFont
  GumungGagye/GumungGagye.xcodeproj/project.pbxproj
  GumungGagye/GumungGagye/AppFontFile/AppFont.swift
  GumungGagye/GumungGagye/Assets.xcassets/Background/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/Background/background.colorset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/Category/ Vehicle.colorset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/Category/Alcohol.colorset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/Category/Cafe.colorset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/Category/Congratulation.colorset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/Category/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/Category/Education.colorset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/Category/Etc.colorset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/Category/Fashion.colorset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/Category/Food.colorset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/Category/Health.colorset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/Category/Leisure.colorset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/Category/Living.colorset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/Category/Store.colorset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/Category/Traffic.colorset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/GrayScale/Black.colorset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/GrayScale/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/GrayScale/Gray1.colorset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/GrayScale/Gray2.colorset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/GrayScale/Gray3.colorset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/GrayScale/Gray4.colorset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/Primary/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/Primary/Light.colorset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/Primary/Light30.colorset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/Primary/Main.colorset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/Tag/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/Tag/OverPurchasing.colorset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/Tag/OverPurchasingLight.colorset/Contents.json
  GumungGagye/GumungGagye/ContentView.swift
  GumungGagye/GumungGagye/Fonts/Pretendard-Black.otf
  GumungGagye/GumungGagye/Fonts/Pretendard-Bold.otf
  GumungGagye/GumungGagye/Fonts/Pretendard-ExtraBold.otf
  GumungGagye/GumungGagye/Fonts/Pretendard-ExtraLight.otf
  GumungGagye/GumungGagye/Fonts/Pretendard-Light.otf
  GumungGagye/GumungGagye/Fonts/Pretendard-Medium.otf
  GumungGagye/GumungGagye/Fonts/Pretendard-Regular.otf
  GumungGagye/GumungGagye/Fonts/Pretendard-SemiBold.otf
  GumungGagye/GumungGagye/Fonts/Pretendard-Thin.otf
  GumungGagye/GumungGagye/GoogleService-Info.plist
  GumungGagye/GumungGagye/Info.plist
Labels: 👻 Lavine

#20 Feat/#18 make group UI
  GumungGagye/GumungGagye.xcodeproj/project.pbxproj
  GumungGagye/GumungGagye/GoogleService-Info.plist
  GumungGagye/GumungGagye/Group/CreateGroupView.swift
  GumungGagye/GumungGagye/Group/GroupData.swift
  GumungGagye/GumungGagye/Group/GroupMain.swift
  GumungGagye/GumungGagye/Group/GroupNotExistView.swift
  GumungGagye/GumungGagye/Group/GroupRoomView.swift
Labels: 👻 Lavine, 🍱 Add

#24 [FIX] Error
  GumungGagye/GumungGagye.xcodeproj/project.pbxproj
  GumungGagye/GumungGagye/Group/GroupNotExistView.swift
  GumungGagye/GumungGagye/Group/GroupRoomView.swift
Labels: 👻 Lavine

#30 Feat/#28 OverpurchasingView, CategoryListView, CategoryHistoryView
  GumungGagye/GumungGagye.xcodeproj/project.pbxproj
  GumungGagye/GumungGagye/Analysis/AnalysisView.swift
  GumungGagye/GumungGagye/Analysis/CategoryHistoryView.swift
  GumungGagye/GumungGagye/Analysis/CategoryListView.swift
  GumungGagye/GumungGagye/Analysis/OverpurchasingView.swift
  GumungGagye/GumungGagye/CommonView/DividerView.swift
Labels: 🌊 Pado, ✨ Feature

#32 Chore/#29 group comment fix
  GumungGagye/GumungGagye/Group/GroupInfoView.swift
  GumungGagye/GumungGagye/Group/GroupRoomView.swift
  GumungGagye/GumungGagye/Group/GroupSpendView.swift
  GumungGagye/GumungGagye/Group/GroupUserSpendView.swift
  GumungGagye/GumungGagye/Group/GroupViewInside.swift
  GumungGagye/GumungGagye/Group/PersonalDaySpendView.swift
Labels: 👻 Lavine, :hammer: Chore

#38 Design/#36 analysis setting UI
  GumungGagye/GumungGagye.xcodeproj/project.pbxproj
  GumungGagye/GumungGagye/Analysis/AnalysisView.swift
  GumungGagye/GumungGagye/Analysis/CategoryHistoryView.swift
  GumungGagye/GumungGagye/Analysis/CategoryListView.swift
  GumungGagye/GumungGagye/Analysis/ChartsView.swift
  GumungGagye/GumungGagye/Analysis/OverpurchasingView.swift
  GumungGagye/GumungGagye/GumungGagyeApp.swift
  GumungGagye/GumungGagye/Setting/SettingView.swift
Labels: 🌊 Pado, 🎨 Design

#39 Feat/#23 modal view
  GumungGagye/GumungGagye.xcodeproj/project.pbxproj
  GumungGagye/GumungGagye/Assets.xcassets/Category/Vehicle.colorset/Contents.json
  GumungGagye/GumungGagye/Component/Breakdown.swift
  GumungGagye/GumungGagye/Component/Button/MoneyTypeButton.swift
  GumungGagye/GumungGagye/Component/Button/NextButton.swift
  GumungGagye/GumungGagye/Component/Button/SmallButton.swift
  GumungGagye/GumungGagye/Component/CategoryIcon.swift
  GumungGagye/GumungGagye/Component/DateBreakdown.swift
  GumungGagye/GumungGagye/Component/DateTotal.swift
  GumungGagye/GumungGagye/Component/MoveMonth.swift
  GumungGagye/GumungGagye/Component/SectionBar.swift
  GumungGagye/GumungGagye/Modal/AddModalView.swift
  GumungGagye/GumungGagye/Modal/BreakdownWriting.swift
  GumungGagye/GumungGagye/Modal/CategorySheet/ExpenseCategorySheet.swift
  GumungGagye/GumungGagye/Modal/CategorySheet/IncomeCategorySheet.swift
  GumungGagye/GumungGagye/Modal/ConnectView.swift
Labels: 🍓 Berry, ✨ Feature, 🎨 Design

#42 Feat/#31 Add GroupView Calendar
  GumungGagye/GumungGagye.xcodeproj/xcshareddata/xcschemes/GumungGagye.xcscheme
  GumungGagye/GumungGagye/Group/CreateGroupView.swift
  GumungGagye/GumungGagye/Group/GroupSpendView.swift
Labels: 👻 Lavine, ✨ Feature

#45 Chore/#43 Firebase Querying TimeStamp
  GumungGagye/GumungGagye.xcodeproj/project.pbxproj
  GumungGagye/GumungGagye/Group/CreateGroupView.swift
  GumungGagye/GumungGagye/Group/GroupData.swift
  GumungGagye/GumungGagye/Group/GroupSpendView.swift
  GumungGagye/GumungGagye/Group/PersonalDaySpendView.swift
Labels: 👻 Lavine, :hammer: Chore

#49 Design/#48 add modal view small button
  GumungGagye/GumungGagye/Budget/MainBudgetView.swift
  GumungGagye/GumungGagye/Component/Button/SmallButton.swift
  GumungGagye/GumungGagye/Modal/BreakdownWriting.swift
Labels: 🍓 Berry, 🔥 Delete, 🎨 Design

#51 Chore/#46 fix group view
  GumungGagye/GumungGagye/Group/CreateGroupView.swift
  GumungGagye/GumungGagye/Group/GroupMain.swift
  GumungGagye/GumungGagye/Group/GroupNotExistView.swift
  GumungGagye/GumungGagye/Group/GroupRoomView.swift
  GumungGagye/GumungGagye/Group/GroupViewInside.swift
Labels: 👻 Lavine, :hammer: Chore

#52 Chore/#46 fix group view
  GumungGagye/GumungGagye.xcodeproj/project.pbxproj
  GumungGagye/GumungGagye/Group/CreateGroupView.swift
  GumungGagye/GumungGagye/Group/GroupData.swift
  GumungGagye/GumungGagye/Group/GroupNotExistView.swift
  GumungGagye/GumungGagye/Group/GroupRoomView.swift
  GumungGagye/GumungGagye/GumungGagyeApp.swift
Labels: 👻 Lavine, :hammer: Chore

#53 [CHORE] Fix Group List View (Firebase SingleTon Design Pattern Method)
  GumungGagye/GumungGagye.xcodeproj/project.pbxproj
  GumungGagye/GumungGagye/Group/GroupData.swift
  GumungGagye/GumungGagye/Group/GroupNotExistView.swift
  GumungGagye/GumungGagye/GumungGagyeApp.swift
Labels: 👻 Lavine, :hammer: Chore

#55 [Feat] - Apple Login 수정
  GumungGagye/GumungGagye.xcodeproj/project.pbxproj
  GumungGagye/GumungGagye/CommonView/MainView.swift
  GumungGagye/GumungGagye/Onboarding/PreStart.swift
  GumungGagye/GumungGagye/Onboarding/RootView.swift
  GumungGagye/GumungGagye/Setting/SettingView.swift
Labels: 🐲 N.D

#58 Chore/#46 fix group view
  GumungGagye/GumungGagye.xcodeproj/project.pbxproj
  GumungGagye/GumungGagye/FirebaseQuery/AccountData.swift
  GumungGagye/GumungGagye/FirebaseQuery/FirebaseController.swift
  GumungGagye/GumungGagye/FirebaseQuery/GroupData.swift
  GumungGagye/GumungGagye/FirebaseQuery/UserData.swift
  GumungGagye/GumungGagye/Group/GroupData.swift
  GumungGagye/GumungGagye/Group/GroupInfoView.swift
  GumungGagye/GumungGagye/Group/GroupNotExistView.swift
  GumungGagye/GumungGagye/Group/GroupRoomView.swift
Labels: 👻 Lavine, :hammer: Chore

#61 [Feat] - InsertUserProfile
  GumungGagye/GumungGagye.xcodeproj/project.pbxproj
  GumungGagye/GumungGagye/Onboarding/Authentication/SettingsView.swift
  GumungGagye/GumungGagye/Onboarding/AuthenticationView.swift
  GumungGagye/GumungGagye/Onboarding/BankCardPayView.swift
  GumungGagye/GumungGagye/Onboarding/Firestore/InputUserData.swift
  GumungGagye/GumungGagye/Onboarding/Firestore/UserManager.swift
  GumungGagye/GumungGagye/Onboarding/PreStart.swift
  GumungGagye/GumungGagye/Onboarding/Profile/ProfileView.swift
  GumungGagye/GumungGagye/Onboarding/RootView.swift
  GumungGagye/GumungGagye/Onboarding/SelectingBudget.swift
  GumungGagye/GumungGagye/Onboarding/SelectingName.swift
  GumungGagye/GumungGagye/Onboarding/Utilities/LoginButton.swift
  GumungGagye/GumungGagye/Setting/SettingView.swift
Labels: 🐲 N.D, ✨ Feature

#62 Chore/#46 fix group view
  GumungGagye/GumungGagye/Group/GroupInfoView.swift
  GumungGagye/GumungGagye/Group/GroupMain.swift
  GumungGagye/GumungGagye/Group/GroupNotExistView.swift
  GumungGagye/GumungGagye/Group/GroupRoomView.swift
  GumungGagye/GumungGagye/Group/GroupViewInside.swift
  GumungGagye/GumungGagye/Onboarding/RootView.swift
Labels: 👻 Lavine, :hammer: Chore

#64 Feat/#57 Data Processing Firebase
  GumungGagye/GumungGagye.xcodeproj/project.pbxproj
  GumungGagye/GumungGagye/Assets.xcassets/imagetest.imageset/8DB1F9EE-3515-4ED4-8B57-7FEA6939844D_1_105_c.jpeg
  GumungGagye/GumungGagye/Assets.xcassets/imagetest.imageset/Contents.json
  GumungGagye/GumungGagye/Data/InsertUserData.swift
  GumungGagye/GumungGagye/Onboarding/AuthenticationView.swift
  GumungGagye/GumungGagye/Onboarding/BankCardPayView.swift
  GumungGagye/GumungGagye/Onboarding/Firestore/InputUserData.swift
  GumungGagye/GumungGagye/Onboarding/Firestore/UserManager.swift
  GumungGagye/GumungGagye/Onboarding/PreStart.swift
  GumungGagye/GumungGagye/Onboarding/RootView.swift
  GumungGagye/GumungGagye/Onboarding/SelectingBank.swift
  GumungGagye/GumungGagye/Onboarding/SelectingBudget.swift
  GumungGagye/GumungGagye/Onboarding/SelectingName.swift
  GumungGagye/GumungGagye/Onboarding/SelectingUserImage.swift
  GumungGagye/GumungGagye/Onboarding/Utilities/BankCardPay.swift
  GumungGagye/GumungGagye/Onboarding/Utilities/ImagePicker.swift
  GumungGagye/GumungGagye/Onboarding/Utilities/LoginButton.swift
  GumungGagye/GumungGagye/Setting/SettingView.swift
Labels: 🐲 N.D, ✨ Feature

#68 Chore/#56 fix history view
  GumungGagye/GumungGagye.xcodeproj/project.pbxproj
  GumungGagye/GumungGagye/Budget/MainBudgetView.swift
  GumungGagye/GumungGagye/Component/Breakdown.swift
  GumungGagye/GumungGagye/Component/DateBreakdown.swift
  GumungGagye/GumungGagye/Component/OverPurchaseTag.swift
  GumungGagye/GumungGagye/Component/SecretTag.swift
  GumungGagye/GumungGagye/Group/CreateGroupView.swift
  GumungGagye/GumungGagye/Group/GroupUserSpendView.swift
  GumungGagye/GumungGagye/Modal/AddModalView.swift
  GumungGagye/GumungGagye/Modal/BreakdownWriting.swift
  GumungGagye/GumungGagye/Modal/CategorySheet/ExpenseCategorySheet.swift
  GumungGagye/GumungGagye/Modal/CategorySheet/IncomeCategorySheet.swift
Labels: 🍀 Lina, :hammer: Chore, 🎨 Design

#69 Feat/#67 delete firebase user
  GumungGagye/GumungGagye/Onboarding/Authentication/AuthenticationManager.swift
  GumungGagye/GumungGagye/Onboarding/Authentication/SettingsView.swift
  GumungGagye/GumungGagye/Onboarding/SelectingUserImage.swift
  GumungGagye/GumungGagye/Setting/SettingView.swift
Labels: 🐲 N.D, ✨ Feature

#72 [Move] - Move Firestore Folder
  GumungGagye/GumungGagye.xcodeproj/project.pbxproj
  GumungGagye/GumungGagye/Data/InsertUserData.swift
  GumungGagye/GumungGagye/Firestore/InputUserData.swift
  GumungGagye/GumungGagye/Firestore/UserManager.swift
  GumungGagye/GumungGagye/Onboarding/Authentication/SettingsView.swift
  GumungGagye/GumungGagye/Onboarding/SelectingUserImage.swift
Labels: 🐲 N.D, :truck: Move

#74 Design/#59 analysis view design
  GumungGagye/GumungGagye/Analysis/AnalysisView.swift
  GumungGagye/GumungGagye/Analysis/CategoryHistoryView.swift
  GumungGagye/GumungGagye/Analysis/ChartsView.swift
  GumungGagye/GumungGagye/Analysis/OverpurchasingView.swift
  GumungGagye/GumungGagye/Analysis/TopContentView.swift
Labels: 🌊 Pado, 🎨 Design

#75 Feat/#70 fix onboarding
  GumungGagye/GumungGagye/Firestore/InputUserData.swift
  GumungGagye/GumungGagye/Firestore/UserManager.swift
  GumungGagye/GumungGagye/Onboarding/Authentication/SettingsView.swift
  GumungGagye/GumungGagye/Onboarding/BankCardPayView.swift
  GumungGagye/GumungGagye/Onboarding/RootView.swift
  GumungGagye/GumungGagye/Onboarding/SelectingBank.swift
  GumungGagye/GumungGagye/Onboarding/SelectingBankView.swift
  GumungGagye/GumungGagye/Onboarding/SelectingBudget.swift
  GumungGagye/GumungGagye/Onboarding/SelectingBudgetView.swift
  GumungGagye/GumungGagye/Onboarding/SelectingUserImage.swift
  GumungGagye/GumungGagye/Setting/SettingView.swift
Labels: 🐲 N.D, :hammer: Chore

#76 Chore/#46 fix group view
  GumungGagye/GumungGagye.xcodeproj/project.pbxproj
  GumungGagye/GumungGagye/CommonView/MainView.swift
  GumungGagye/GumungGagye/FirebaseQuery/FirebaseController.swift
  GumungGagye/GumungGagye/FirebaseQuery/UserData.swift
  GumungGagye/GumungGagye/Firestore/UserManager.swift
  GumungGagye/GumungGagye/Group/CreateGroupView.swift
  GumungGagye/GumungGagye/Group/GroupMain.swift
  GumungGagye/GumungGagye/Group/GroupNotExistView.swift
  GumungGagye/GumungGagye/Group/GroupRoomView.swift
  GumungGagye/GumungGagye/Group/GroupViewInside.swift
Labels: 👻 Lavine, :hammer: Chore

#79 [FEAT] #77 Input Firebase Account Data
  GumungGagye/GumungGagye.xcodeproj/project.pbxproj
  GumungGagye/GumungGagye/Modal/AddModalView.swift
  GumungGagye/GumungGagye/Modal/BreakdownWriting.swift
Labels: 🐲 N.D, ✨ Feature

#82 [Feat] #81 Input Firebase Income Data
  GumungGagye/GumungGagye.xcodeproj/project.pbxproj
  GumungGagye/GumungGagye/Firestore/AccountManager.swift
  GumungGagye/GumungGagye/Firestore/AccountManager2.swift
  GumungGagye/GumungGagye/Firestore/AddModalViewModel.swift
  GumungGagye/GumungGagye/Firestore/Model/IncomeData.swift
  GumungGagye/GumungGagye/Modal/AddModalView.swift
  GumungGagye/GumungGagye/Modal/BreakdownWriting.swift
Labels: 🐲 N.D, ✨ Feature

#87 [FEAT] Category Icon
  GumungGagye/GumungGagye.xcodeproj/project.pbxproj
  GumungGagye/GumungGagye/Component/Breakdown.swift
  GumungGagye/GumungGagye/Component/CategoryIcon.swift
  GumungGagye/GumungGagye/Modal/CategorySheet/ExpenseCategorySheet.swift
  GumungGagye/GumungGagye/Modal/CategorySheet/IncomeCategorySheet.swift
Labels: 🌊 Pado, ✨ Feature

#88 Chore/#46 fix group view
  GumungGagye/GumungGagye.xcodeproj/project.pbxproj
  GumungGagye/GumungGagye/FirebaseQuery/FirebaseController.swift
  GumungGagye/GumungGagye/FirebaseQuery/UserData.swift
  GumungGagye/GumungGagye/Group/GroupMain.swift
  GumungGagye/GumungGagye/Group/GroupViewInside.swift
Labels: 👻 Lavine, :hammer: Chore

#93 [FEAT] Move Month
  GumungGagye/GumungGagye/Analysis/AnalysisView.swift
  GumungGagye/GumungGagye/Budget/MainBudgetView.swift
  GumungGagye/GumungGagye/Component/MoveMonth.swift
Labels: 🌊 Pado, ✨ Feature

#94 [FEAT] Move Month Limit
  GumungGagye/GumungGagye/Component/MoveMonth.swift
Labels: 🌊 Pado, ✨ Feature

#95 Chore/#46 fix group view
  GumungGagye/GumungGagye.xcodeproj/project.pbxproj
  GumungGagye/GumungGagye/Group/CodeFieldView.swift
  GumungGagye/GumungGagye/Group/CreateGroupView.swift
  GumungGagye/GumungGagye/Group/GroupInfoView.swift
  GumungGagye/GumungGagye/Group/GroupRoomView.swift
Labels: 👻 Lavine, :hammer: Chore

#97 Feat/#96 add modal view
  GumungGagye/GumungGagye.xcodeproj/project.pbxproj
  GumungGagye/GumungGagye/AccountModal/DetailModalView/BillmodalView.swift
  GumungGagye/GumungGagye/AccountModal/DetailModalView/CategoryInfo.swift
  GumungGagye/GumungGagye/AccountModal/DetailModalView/CategorymodelView.swift
  GumungGagye/GumungGagye/AccountModal/DetailModalView/ContentmodelView.swift
  GumungGagye/GumungGagye/AccountModal/DetailModalView/DatemodalView.swift
  GumungGagye/GumungGagye/AccountModal/DetailModalView/DetailCategoryView.swift
  GumungGagye/GumungGagye/AccountModal/DetailModalView/ExpenseCategorySheetView.swift
  GumungGagye/GumungGagye/AccountModal/DetailModalView/IncomeCategorySheetView.swift
  GumungGagye/GumungGagye/AccountModal/DetailModalView/SpendOpenView.swift
  GumungGagye/GumungGagye/AccountModal/DetailModalView/SpendOverConsumeView.swift
  GumungGagye/GumungGagye/AccountModal/IncomeModalView.swift
  GumungGagye/GumungGagye/AccountModal/ModalView.swift
  GumungGagye/GumungGagye/AccountModal/SpendModalView.swift
  GumungGagye/GumungGagye/AccountModal/TopModalView.swift
  GumungGagye/GumungGagye/Assets.xcassets/Union.imageset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/Union.imageset/Union.png
  GumungGagye/GumungGagye/Assets.xcassets/Union.imageset/Union@2x.png
  GumungGagye/GumungGagye/Assets.xcassets/Union.imageset/Union@3x.png
  GumungGagye/GumungGagye/Budget/MainBudgetView.swift
  GumungGagye/GumungGagye/Firestore/AccountManager2.swift
  GumungGagye/GumungGagye/GumungGagyeApp.swift
  GumungGagye/GumungGagye/Modal/AddModalView.swift
  GumungGagye/GumungGagye/Onboarding/Utilities/BankCardPay.swift
Labels: 🐲 N.D, ✨ Feature

#98 Chore/#46 fix group view
  GumungGagye/GumungGagye.xcodeproj/project.pbxproj
  GumungGagye/GumungGagye/Group/CreateGroupView.swift
  GumungGagye/GumungGagye/Group/GroupViewInside.swift
  GumungGagye/GumungGagye/Info.plist
Labels: 👻 Lavine, :hammer: Chore

#99 Chore/#46 fix group view
  GumungGagye/GumungGagye/CommonView/MainView.swift
  GumungGagye/GumungGagye/Group/GroupMain.swift
  GumungGagye/GumungGagye/Group/GroupRoomView.swift
  GumungGagye/GumungGagye/Group/GroupViewInside.swift
Labels: 👻 Lavine, :hammer: Chore

#100 Asset/#92 Add Logo Image
  GumungGagye/GumungGagye/Assets.xcassets/AppIcon.appiconset/AppIcon.png
  GumungGagye/GumungGagye/Assets.xcassets/AppIcon.appiconset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/AppLogo/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/AppLogo/Logo_HorizontalType.imageset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/AppLogo/Logo_HorizontalType.imageset/Logo_HorizontalType 1.svg
  GumungGagye/GumungGagye/Assets.xcassets/AppLogo/Logo_HorizontalType.imageset/Logo_HorizontalType 2.svg
  GumungGagye/GumungGagye/Assets.xcassets/AppLogo/Logo_HorizontalType.imageset/Logo_HorizontalType.svg
  GumungGagye/GumungGagye/Assets.xcassets/AppLogo/Logo_VerticalType.imageset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/AppLogo/Logo_VerticalType.imageset/Logo_VerticalType 1.svg
  GumungGagye/GumungGagye/Assets.xcassets/AppLogo/Logo_VerticalType.imageset/Logo_VerticalType 2.svg
  GumungGagye/GumungGagye/Assets.xcassets/AppLogo/Logo_VerticalType.imageset/Logo_VerticalType.svg
Labels: 🍓 Berry, 🎨 Design

#104 Asset/#92 Add Tab Bar Icon
  GumungGagye/GumungGagye/Assets.xcassets/TabBarIcon/AnalysisIconAbled.imageset/AnalysisIconAbled 1.svg
  GumungGagye/GumungGagye/Assets.xcassets/TabBarIcon/AnalysisIconAbled.imageset/AnalysisIconAbled 2.svg
  GumungGagye/GumungGagye/Assets.xcassets/TabBarIcon/AnalysisIconAbled.imageset/AnalysisIconAbled.svg
  GumungGagye/GumungGagye/Assets.xcassets/TabBarIcon/AnalysisIconAbled.imageset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/TabBarIcon/AnalysisIconDisabled.imageset/AnalysisIconDisabled 1.svg
  GumungGagye/GumungGagye/Assets.xcassets/TabBarIcon/AnalysisIconDisabled.imageset/AnalysisIconDisabled 2.svg
  GumungGagye/GumungGagye/Assets.xcassets/TabBarIcon/AnalysisIconDisabled.imageset/AnalysisIconDisabled.svg
  GumungGagye/GumungGagye/Assets.xcassets/TabBarIcon/AnalysisIconDisabled.imageset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/TabBarIcon/BudgetIconAbled.imageset/BudgetIconAbled 1.svg
  GumungGagye/GumungGagye/Assets.xcassets/TabBarIcon/BudgetIconAbled.imageset/BudgetIconAbled 2.svg
  GumungGagye/GumungGagye/Assets.xcassets/TabBarIcon/BudgetIconAbled.imageset/BudgetIconAbled.svg
  GumungGagye/GumungGagye/Assets.xcassets/TabBarIcon/BudgetIconAbled.imageset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/TabBarIcon/BudgetIconDisabled.imageset/BudgetIconDisabled 1.svg
  GumungGagye/GumungGagye/Assets.xcassets/TabBarIcon/BudgetIconDisabled.imageset/BudgetIconDisabled 2.svg
  GumungGagye/GumungGagye/Assets.xcassets/TabBarIcon/BudgetIconDisabled.imageset/BudgetIconDisabled.svg
  GumungGagye/GumungGagye/Assets.xcassets/TabBarIcon/BudgetIconDisabled.imageset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/TabBarIcon/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/TabBarIcon/GroupIconAbled.imageset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/TabBarIcon/GroupIconAbled.imageset/GroupIconAbled 1.svg
  GumungGagye/GumungGagye/Assets.xcassets/TabBarIcon/GroupIconAbled.imageset/GroupIconAbled 2.svg
  GumungGagye/GumungGagye/Assets.xcassets/TabBarIcon/GroupIconAbled.imageset/GroupIconAbled.svg
  GumungGagye/GumungGagye/Assets.xcassets/TabBarIcon/GroupIconDisabled.imageset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/TabBarIcon/GroupIconDisabled.imageset/GroupIconDisabled 1.svg
  GumungGagye/GumungGagye/Assets.xcassets/TabBarIcon/GroupIconDisabled.imageset/GroupIconDisabled 2.svg
  GumungGagye/GumungGagye/Assets.xcassets/TabBarIcon/GroupIconDisabled.imageset/GroupIconDisabled.svg
  GumungGagye/GumungGagye/Assets.xcassets/TabBarIcon/SettingIconAbled.imageset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/TabBarIcon/SettingIconAbled.imageset/SettingIconAbled 1.svg
  GumungGagye/GumungGagye/Assets.xcassets/TabBarIcon/SettingIconAbled.imageset/SettingIconAbled 2.svg
  GumungGagye/GumungGagye/Assets.xcassets/TabBarIcon/SettingIconAbled.imageset/SettingIconAbled.svg
  GumungGagye/GumungGagye/Assets.xcassets/TabBarIcon/SettingIconDisabled.imageset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/TabBarIcon/SettingIconDisabled.imageset/SettingIconDisabled 1.svg
  GumungGagye/GumungGagye/Assets.xcassets/TabBarIcon/SettingIconDisabled.imageset/SettingIconDisabled 2.svg
  GumungGagye/GumungGagye/Assets.xcassets/TabBarIcon/SettingIconDisabled.imageset/SettingIconDisabled.svg
Labels: 🍓 Berry, 🎨 Design

#105 Chore/#46 fix group view
  GumungGagye/GumungGagye.xcodeproj/project.pbxproj
  GumungGagye/GumungGagye/Assets.xcassets/SelectingBankImage/농협은행.imageset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/SelectingBankImage/농협카드.imageset/Contents.json
  GumungGagye/GumungGagye/CommonView/MainView.swift
  GumungGagye/GumungGagye/FirebaseQuery/FirebaseController.swift
  GumungGagye/GumungGagye/FirebaseQuery/UserData.swift
  GumungGagye/GumungGagye/Firestore/UserManager.swift
  GumungGagye/GumungGagye/Group/GroupInfoView.swift
  GumungGagye/GumungGagye/Group/GroupMain.swift
  GumungGagye/GumungGagye/Group/GroupRankingView.swift
  GumungGagye/GumungGagye/Onboarding/RootView.swift
  GumungGagye/GumungGagye/Setting/SettingView.swift
Labels: 👻 Lavine, :hammer: Chore

#106 [CHORE] Fix Group Icon
  GumungGagye/GumungGagye/Group/GroupRoomView.swift
Labels: :hammer: Chore, ✨ Feature

#107 Feat/#90 add data budget
  GumungGagye/GumungGagye.xcodeproj/project.pbxproj
  GumungGagye/GumungGagye/AccountModal/DetailModalView/BillmodalView.swift
  GumungGagye/GumungGagye/AccountModal/DetailModalView/CategoryInfo.swift
  GumungGagye/GumungGagye/AccountModal/DetailModalView/SpendOverConsumeView.swift
  GumungGagye/GumungGagye/AccountModal/ModalView.swift
  GumungGagye/GumungGagye/AccountModal/SpendModalView.swift
  GumungGagye/GumungGagye/Analysis/CategoryHistoryView.swift
  GumungGagye/GumungGagye/Analysis/OverpurchasingView.swift
  GumungGagye/GumungGagye/Budget/ConsListView.swift
  GumungGagye/GumungGagye/Budget/CurrentAssetView.swift
  GumungGagye/GumungGagye/Budget/MainBudgetView.swift
  GumungGagye/GumungGagye/Budget/TargetBudgetView.swift
  GumungGagye/GumungGagye/Component/Breakdown.swift
  GumungGagye/GumungGagye/Component/CategoryIcon.swift
  GumungGagye/GumungGagye/Component/DateBreakdown.swift
  GumungGagye/GumungGagye/Component/OpenTag.swift
  GumungGagye/GumungGagye/FirebaseQuery/AccountData.swift
  GumungGagye/GumungGagye/FirebaseQuery/FirebaseController.swift
  GumungGagye/GumungGagye/Firestore/AccountManager2.swift
  GumungGagye/GumungGagye/Firestore/AccountManager3.swift
  GumungGagye/GumungGagye/Firestore/AddModalViewModel.swift
  GumungGagye/GumungGagye/Firestore/Model/ExpenseData.swift
  GumungGagye/GumungGagye/Firestore/Model/IncomeData.swift
  GumungGagye/GumungGagye/Firestore/Model/SpendData.swift
  GumungGagye/GumungGagye/Firestore/ReadAccountManager.swift
  GumungGagye/GumungGagye/Modal/BreakdownWriting.swift
  GumungGagye/GumungGagye/Modal/CategorySheet/ExpenseCategorySheet.swift
  GumungGagye/GumungGagye/Modal/CategorySheet/IncomeCategorySheet.swift
Labels: 🍀 Lina, ✨ Feature

#109 [FEAT] Store Budget Data
  GumungGagye/GumungGagye/AccountModal/ModalView.swift
  GumungGagye/GumungGagye/Budget/MainBudgetView.swift
  GumungGagye/GumungGagye/Firestore/AccountManager2.swift
Labels: 👻 Lavine, ✨ Feature

#110 [FEAT] Code Refactoring
  GumungGagye/GumungGagye.xcodeproj/project.pbxproj
  GumungGagye/GumungGagye/AccountModal/ModalView.swift
  GumungGagye/GumungGagye/Component/Breakdown.swift
  GumungGagye/GumungGagye/FirebaseQuery/AccountData.swift
  GumungGagye/GumungGagye/Firestore/AccountManager.swift
  GumungGagye/GumungGagye/Firestore/AccountManager3.swift
  GumungGagye/GumungGagye/Firestore/BudgetFirebaseManager.swift
  GumungGagye/GumungGagye/Firestore/FirebaseController.swift
  GumungGagye/GumungGagye/Firestore/Model/GroupData.swift
  GumungGagye/GumungGagye/Firestore/Model/IncomeData.swift
  GumungGagye/GumungGagye/Firestore/Model/SpendData.swift
  GumungGagye/GumungGagye/Firestore/Model/UserData.swift
  GumungGagye/GumungGagye/Firestore/ReadAccountManager.swift
  GumungGagye/GumungGagye/Firestore/UserManager.swift
  GumungGagye/GumungGagye/Modal/AddModalView.swift
  GumungGagye/GumungGagye/Modal/BreakdownWriting.swift
  GumungGagye/GumungGagye/Modal/CategorySheet/ExpenseCategorySheet.swift
  GumungGagye/GumungGagye/Modal/CategorySheet/IncomeCategorySheet.swift
Labels: 👻 Lavine, 🔥 Delete

#112 [Fix] Fix Setting View
  GumungGagye/GumungGagye/Onboarding/SelectingBudgetView.swift
  GumungGagye/GumungGagye/Setting/SettingView.swift
Labels: 🐲 N.D, :hammer: Chore

#113 Feat/#90 add data budget
  GumungGagye/GumungGagye.xcodeproj/project.pbxproj
  GumungGagye/GumungGagye/AccountModal/DetailModalView/BillmodalView.swift
  GumungGagye/GumungGagye/AccountModal/DetailModalView/CategorySheetView.swift
  GumungGagye/GumungGagye/AccountModal/DetailModalView/CategorymodelView.swift
  GumungGagye/GumungGagye/AccountModal/DetailModalView/DetailCategoryView.swift
  GumungGagye/GumungGagye/Analysis/CategoryHistoryView.swift
  GumungGagye/GumungGagye/Analysis/CategoryListView.swift
  GumungGagye/GumungGagye/Budget/TargetBudgetView.swift
  GumungGagye/GumungGagye/Component/CategorySelected.swift
Labels: 🍀 Lina, ✨ Feature

#114 Feat/#108 firebase budget view
  GumungGagye/GumungGagye.xcodeproj/project.pbxproj
  GumungGagye/GumungGagye/Budget/BudgetPostView.swift
  GumungGagye/GumungGagye/Budget/MainBudgetView.swift
  GumungGagye/GumungGagye/Component/Breakdown.swift
  GumungGagye/GumungGagye/Component/DateBreakdown.swift
  GumungGagye/GumungGagye/Firestore/BudgetFirebaseManager.swift
Labels: 👻 Lavine, ✨ Feature

#115 Feat/#90 add data budget
  GumungGagye/GumungGagye/AccountModal/DetailModalView/CategoryInfo.swift
  GumungGagye/GumungGagye/Budget/CurrentAssetView.swift
  GumungGagye/GumungGagye/Budget/MainBudgetView.swift
  GumungGagye/GumungGagye/Budget/TargetBudgetView.swift
  GumungGagye/GumungGagye/CommonView/MainView.swift
Labels: 🍀 Lina, :hammer: Chore

#116 Fix/#111 fix setting view
  GumungGagye/GumungGagye/AccountModal/DetailModalView/DatemodalView.swift
  GumungGagye/GumungGagye/AccountModal/DetailModalView/DetailCategoryView.swift
  GumungGagye/GumungGagye/Assets.xcassets/GeneralIcon/Chevron.right.midi.gray3.imageset/Chevron.right.midi.gray3.svg
  GumungGagye/GumungGagye/Assets.xcassets/GeneralIcon/Chevron.right.midi.gray3.imageset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/GeneralIcon/Chevron.right.thick.gray3.imageset/Chevron.right.thick.gray3.svg
  GumungGagye/GumungGagye/Assets.xcassets/GeneralIcon/Chevron.right.thick.gray3.imageset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/SelectingBankImage/농협은행.imageset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/SelectingBankImage/농협카드.imageset/Contents.json
  GumungGagye/GumungGagye/Component/CategorySelected.swift
  GumungGagye/GumungGagye/Component/MoveMonth.swift
  GumungGagye/GumungGagye/Info.plist
  GumungGagye/GumungGagye/Setting/SettingView.swift
Labels: 🐲 N.D, :hammer: Chore

#118 [CHORE] budget main view only spend date
  GumungGagye/GumungGagye/Budget/BudgetPostView.swift
  GumungGagye/GumungGagye/Budget/MainBudgetView.swift
  GumungGagye/GumungGagye/Firestore/BudgetFirebaseManager.swift
Labels: 👻 Lavine, :hammer: Chore

#120 [CHORE] Fix Firebase main budget view
  GumungGagye/GumungGagye/Firestore/BudgetFirebaseManager.swift
Labels: 👻 Lavine, :hammer: Chore

#122 Feat/#119 budget sum
  GumungGagye/GumungGagye/Budget/BudgetPostView.swift
  GumungGagye/GumungGagye/Budget/CurrentAssetView.swift
  GumungGagye/GumungGagye/Budget/MainBudgetView.swift
  GumungGagye/GumungGagye/Budget/TargetBudgetView.swift
  GumungGagye/GumungGagye/Component/Breakdown.swift
Labels: 🌊 Pado, ✨ Feature

#124 Chore/#46 fix group view
  GumungGagye/GumungGagye/AccountModal/DetailModalView/SpendOpenView.swift
  GumungGagye/GumungGagye/AccountModal/DetailModalView/SpendOverConsumeView.swift
  GumungGagye/GumungGagye/AccountModal/SpendModalView.swift
  GumungGagye/GumungGagye/Budget/BudgetPostView.swift
  GumungGagye/GumungGagye/Component/Breakdown.swift
  GumungGagye/GumungGagye/Group/GroupInfoView.swift
  GumungGagye/GumungGagye/Group/GroupViewInside.swift
Labels: 👻 Lavine, :hammer: Chore, ✨ Feature
