Repository JungDohyeon/MC3-Team14-FutureStarz, pull requests merged in 2023-08, with the labels that each got.

#128 [Feat] #127 Add Analysis Top View
  GumungGagye/GumungGagye.xcodeproj/project.pbxproj
  GumungGagye/GumungGagye/Analysis/AnalysisView.swift
  GumungGagye/GumungGagye/Analysis/Model/AnalysisData.swift
  GumungGagye/GumungGagye/Analysis/Model/AnalysisModel.swift
  GumungGagye/GumungGagye/Analysis/OverpurchasingView.swift
  GumungGagye/GumungGagye/Firestore/BudgetFirebaseManager.swift
  GumungGagye/GumungGagye/Firestore/FirebaseController.swift
Labels: 🐲 N.D, ✨ Feature

#129 Chore/#46 fix group view
  GumungGagye/GumungGagye/Analysis/AnalysisView.swift
  GumungGagye/GumungGagye/Budget/BudgetPostView.swift
  GumungGagye/GumungGagye/Budget/MainBudgetView.swift
  GumungGagye/GumungGagye/Budget/TargetBudgetView.swift
  GumungGagye/GumungGagye/Component/MoveMonth.swift
  GumungGagye/GumungGagye/Firestore/BudgetFirebaseManager.swift
  GumungGagye/GumungGagye/Group/GroupInfoView.swift
  GumungGagye/GumungGagye/Group/GroupViewInside.swift
Labels: 👻 Lavine, :hammer: Chore, ✨ Feature

#131 [Fix] Onboarding View
  GumungGagye/GumungGagye.xcodeproj/project.pbxproj
  GumungGagye/GumungGagye.xcodeproj/xcshareddata/xcschemes/GumungGagye.xcscheme
  GumungGagye/GumungGagye/AccountModal/ModalView.swift
  GumungGagye/GumungGagye/Onboarding/BankCardPayView.swift
  GumungGagye/GumungGagye/Onboarding/SelectingBank.swift
  GumungGagye/GumungGagye/Onboarding/SelectingBankView.swift
  GumungGagye/GumungGagye/Onboarding/SelectingBudget.swift
  GumungGagye/GumungGagye/Onboarding/SelectingBudgetView.swift
  GumungGagye/GumungGagye/Onboarding/Utilities/OnboardingNextButton.swift
  GumungGagye/GumungGagye/Setting/SettingView.swift
Labels: 🐲 N.D, 🎨 Design

#132 Chore/#46 fix group view
  GumungGagye/GumungGagye/AccountModal/DetailModalView/DatemodalView.swift
  GumungGagye/GumungGagye/Budget/MainBudgetView.swift
  GumungGagye/GumungGagye/Budget/TargetBudgetView.swift
  GumungGagye/GumungGagye/Group/GroupMain.swift
  GumungGagye/GumungGagye/Group/GroupRoomView.swift
  GumungGagye/GumungGagye/Onboarding/RootView.swift
Labels: 👻 Lavine, :hammer: Chore

#134 [CHORE] Fix Main Graph
  GumungGagye/GumungGagye/Budget/TargetBudgetView.swift
Labels: 👻 Lavine, :hammer: Chore, 🐛 Bug

#137 Chore/#46 fix group view
  GumungGagye/GumungGagye.xcodeproj/project.pbxproj
  GumungGagye/GumungGagye/AccountModal/ModalView.swift
  GumungGagye/GumungGagye/Budget/BudgetPostView.swift
  GumungGagye/GumungGagye/Budget/MainBudgetView.swift
  GumungGagye/GumungGagye/CommonView/MainView.swift
  GumungGagye/GumungGagye/Component/Breakdown.swift
  GumungGagye/GumungGagye/Firestore/BudgetFirebaseManager.swift
  GumungGagye/GumungGagye/Firestore/FirebaseController.swift
  GumungGagye/GumungGagye/Firestore/Model/GroupData.swift
  GumungGagye/GumungGagye/Group/CreateGroupView.swift
  GumungGagye/GumungGagye/Group/GroupMain.swift
  GumungGagye/GumungGagye/Group/GroupNotExistView.swift
  GumungGagye/GumungGagye/Group/GroupRoomView.swift
  GumungGagye/GumungGagye/Group/GroupViewInside.swift
  GumungGagye/GumungGagye/Group/UserNoSpendView.swift
Labels: 👻 Lavine, :hammer: Chore

#141 DESIGN/#140 Chore SettingView & OnboardingView
  GumungGagye/GumungGagye/Onboarding/SelectingBank.swift
  GumungGagye/GumungGagye/Onboarding/SelectingBankView.swift
  GumungGagye/GumungGagye/Setting/SettingView.swift
Labels: 🍓 Berry, :hammer: Chore, 🔥 Delete, 🎨 Design

#144 Chore/#133 chore UI
  GumungGagye/GumungGagye/AccountModal/DetailModalView/BillmodalView.swift
  GumungGagye/GumungGagye/AccountModal/DetailModalView/CategorySheetView.swift
  GumungGagye/GumungGagye/AccountModal/DetailModalView/CategorymodelView.swift
  GumungGagye/GumungGagye/AccountModal/DetailModalView/ContentmodelView.swift
  GumungGagye/GumungGagye/AccountModal/DetailModalView/DatemodalView.swift
  GumungGagye/GumungGagye/AccountModal/IncomeModalView.swift
  GumungGagye/GumungGagye/AccountModal/SpendModalView.swift
  GumungGagye/GumungGagye/Group/CreateGroupView.swift
  GumungGagye/GumungGagye/Onboarding/SelectingBudget.swift
Labels: 🍀 Lina, 🎨 Design

#145 Chore/#133 chore UI
  GumungGagye/GumungGagye.xcodeproj/project.pbxproj
  GumungGagye/GumungGagye/Onboarding/SelectingBudget.swift
  GumungGagye/GumungGagye/Setting/SelectingBankView.swift
  GumungGagye/GumungGagye/Setting/SelectingBudgetView.swift
Labels: 🍀 Lina, 🎨 Design

#146 Chore/#46 fix group view
  GumungGagye/GumungGagye/AccountModal/DetailModalView/DatemodalView.swift
  GumungGagye/GumungGagye/Budget/BudgetPostView.swift
  GumungGagye/GumungGagye/Budget/MainBudgetView.swift
  GumungGagye/GumungGagye/Firestore/BudgetFirebaseManager.swift
  GumungGagye/GumungGagye/Firestore/FirebaseController.swift
  GumungGagye/GumungGagye/Group/GroupViewInside.swift
  GumungGagye/GumungGagye/Group/PersonalDaySpendView.swift
Labels: 👻 Lavine, :hammer: Chore, ✨ Feature

#149 Feat/#143 add analysis feature
  GumungGagye/GumungGagye.xcodeproj/project.pbxproj
  GumungGagye/GumungGagye/Analysis/AnalysisView.swift
  GumungGagye/GumungGagye/Analysis/CategoryListDetailView.swift
  GumungGagye/GumungGagye/Analysis/CategoryListView.swift
  GumungGagye/GumungGagye/Analysis/ChartsView.swift
  GumungGagye/GumungGagye/Analysis/OverpurchasingView.swift
  GumungGagye/GumungGagye/Assets.xcassets/AnalysisImage/AlcoholDateBreakdown.imageset/AlcoholDateBreakdown.png
  GumungGagye/GumungGagye/Assets.xcassets/AnalysisImage/AlcoholDateBreakdown.imageset/AlcoholDateBreakdown@2x.png
  GumungGagye/GumungGagye/Assets.xcassets/AnalysisImage/AlcoholDateBreakdown.imageset/AlcoholDateBreakdown@3x.png
  GumungGagye/GumungGagye/Assets.xcassets/AnalysisImage/AlcoholDateBreakdown.imageset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/AnalysisImage/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/AnalysisImage/FashionDateBreakdown.imageset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/AnalysisImage/FashionDateBreakdown.imageset/FashionDateBreakdown.png
  GumungGagye/GumungGagye/Assets.xcassets/AnalysisImage/FashionDateBreakdown.imageset/FashionDateBreakdown@2x.png
  GumungGagye/GumungGagye/Assets.xcassets/AnalysisImage/FashionDateBreakdown.imageset/FashionDateBreakdown@3x.png
  GumungGagye/GumungGagye/Assets.xcassets/AnalysisImage/StoreDateBreakdown.imageset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/AnalysisImage/StoreDateBreakdown.imageset/StoreDateBreakdown.png
  GumungGagye/GumungGagye/Assets.xcassets/AnalysisImage/StoreDateBreakdown.imageset/StoreDateBreakdown@2x.png
  GumungGagye/GumungGagye/Assets.xcassets/AnalysisImage/StoreDateBreakdown.imageset/StoreDateBreakdown@3x.png
  GumungGagye/GumungGagye/Assets.xcassets/AnalysisImage/VehicleDateBreakdown.imageset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/AnalysisImage/VehicleDateBreakdown.imageset/VehicleDateBreakdown.png
  GumungGagye/GumungGagye/Assets.xcassets/AnalysisImage/VehicleDateBreakdown.imageset/VehicleDateBreakdown@2x.png
  GumungGagye/GumungGagye/Assets.xcassets/AnalysisImage/VehicleDateBreakdown.imageset/VehicleDateBreakdown@3x.png
  GumungGagye/GumungGagye/Assets.xcassets/CategorySpend/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/CategorySpend/EducationCategoryList.imageset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/CategorySpend/EducationCategoryList.imageset/EducationCategoryList.png
  GumungGagye/GumungGagye/Assets.xcassets/CategorySpend/EducationCategoryList.imageset/EducationCategoryList@2x.png
  GumungGagye/GumungGagye/Assets.xcassets/CategorySpend/EducationCategoryList.imageset/EducationCategoryList@3x.png
  GumungGagye/GumungGagye/Assets.xcassets/CategorySpend/FashionCategoryList.imageset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/CategorySpend/FashionCategoryList.imageset/FashionCategoryList.png
  GumungGagye/GumungGagye/Assets.xcassets/CategorySpend/FashionCategoryList.imageset/FashionCategoryList@2x.png
  GumungGagye/GumungGagye/Assets.xcassets/CategorySpend/FashionCategoryList.imageset/FashionCategoryList@3x.png
  GumungGagye/GumungGagye/Assets.xcassets/CategorySpend/FoodCategoryList.imageset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/CategorySpend/FoodCategoryList.imageset/FoodCategoryList.png
  GumungGagye/GumungGagye/Assets.xcassets/CategorySpend/FoodCategoryList.imageset/FoodCategoryList@2x.png
  GumungGagye/GumungGagye/Assets.xcassets/CategorySpend/FoodCategoryList.imageset/FoodCategoryList@3x.png
  GumungGagye/GumungGagye/Assets.xcassets/CategorySpend/Frame 583.imageset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/CategorySpend/Frame 583.imageset/Frame 583.png
  GumungGagye/GumungGagye/Assets.xcassets/CategorySpend/Frame 583.imageset/Frame 583@2x.png
  GumungGagye/GumungGagye/Assets.xcassets/CategorySpend/Frame 583.imageset/Frame 583@3x.png
  GumungGagye/GumungGagye/Assets.xcassets/CategorySpend/HealthCategoryList.imageset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/CategorySpend/HealthCategoryList.imageset/HealthCategoryList.png
  GumungGagye/GumungGagye/Assets.xcassets/CategorySpend/HealthCategoryList.imageset/HealthCategoryList@2x.png
  GumungGagye/GumungGagye/Assets.xcassets/CategorySpend/HealthCategoryList.imageset/HealthCategoryList@3x.png
  GumungGagye/GumungGagye/Assets.xcassets/CategorySpend/LivingCategoryList.imageset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/CategorySpend/LivingCategoryList.imageset/LivingCategoryList.png
  GumungGagye/GumungGagye/Assets.xcassets/CategorySpend/LivingCategoryList.imageset/LivingCategoryList@2x.png
  GumungGagye/GumungGagye/Assets.xcassets/CategorySpend/LivingCategoryList.imageset/LivingCategoryList@3x.png
  GumungGagye/GumungGagye/Assets.xcassets/CategorySpend/TrafficCategoryList.imageset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/CategorySpend/TrafficCategoryList.imageset/TrafficCategoryList.png
  GumungGagye/GumungGagye/Assets.xcassets/CategorySpend/TrafficCategoryList.imageset/TrafficCategoryList@2x.png
  GumungGagye/GumungGagye/Assets.xcassets/CategorySpend/TrafficCategoryList.imageset/TrafficCategoryList@3x.png
  GumungGagye/GumungGagye/Assets.xcassets/VehicleDateBreakdown.imageset/Contents.json
  GumungGagye/GumungGagye/Assets.xcassets/VehicleDateBreakdown.imageset/VehicleDateBreakdown.png
  GumungGagye/GumungGagye/Assets.xcassets/VehicleDateBreakdown.imageset/VehicleDateBreakdown@2x.png
  GumungGagye/GumungGagye/Assets.xcassets/VehicleDateBreakdown.imageset/VehicleDateBreakdown@3x.png
  GumungGagye/GumungGagye/Firestore/BudgetFirebaseManager.swift
Labels: 🐲 N.D, ✨ Feature

#153 [Fix] Analysis View
  GumungGagye/GumungGagye/Analysis/AnalysisView.swift
Labels: 🐲 N.D, :hammer: Chore

#154 [CHORE] FIX group ranking
  GumungGagye/GumungGagye/Group/GroupInfoView.swift
  GumungGagye/GumungGagye/Group/GroupRankingView.swift
Labels: 👻 Lavine, :hammer: Chore

#155 [CHORE] Fix Group UI
  GumungGagye/GumungGagye/Group/GroupInfoView.swift
  GumungGagye/GumungGagye/Group/GroupViewInside.swift
  GumungGagye/GumungGagye/Group/PersonalDaySpendView.swift
  GumungGagye/GumungGagye/Group/UserNoSpendView.swift
Labels: 👻 Lavine, :hammer: Chore
